swagger: '2.0'
info:
  version: 0.0.1
  title: Swagger API
host: 'localhost:10010'
basePath: /api
schemes:
  - http
consumes:
  - multipart/form-data
  - application/json
produces:
  - application/json
  - text/plain
paths:
  /v1/user:
    x-swagger-router-controller: controller
    get:
      description: Retrieve a list of users
      operationId: v1_userList
      parameters:
        - name: page
          in: query
          type: integer
          description: Page number of the request
        - name: count
          in: query
          type: integer
          description: Number of categories per page
        - name: filter
          in: query
          type: string
          description: Filter categories based on certain fields
        - name: select
          in: query
          type: string
          description: Comma seperated fields to be displayed
        - name: sort
          in: query
          type: string
          description: sort parameter
      responses:
        '200':
          description: List of the entites
        '400':
          description: Bad parameters
        '404':
          description: No categories to list with the given parameter set.
        '500':
          description: Internal server error
    post:
      description: Create a new user
      operationId: v1_userCreate
      parameters:
        - name: data
          in: body
          description: Payload to create a user
          schema:
            $ref: '#/definitions/user_create'
      responses:
        '200':
          description: List of the entites
        '400':
          description: Bad parameters
        '404':
          description: No categories to list with the given parameter set.
        '500':
          description: Internal server error
  '/v1/user/{id}':
    x-swagger-router-controller: controller
    get:
      description: Retrieve a list of user
      operationId: v1_userShow
      parameters:
        - name: filter
          in: query
          type: string
          description: Filter categories based on certain fields
        - name: select
          in: query
          type: string
          description: Comma seperated fields to be displayed
        - name: id
          in: path
          type: string
          required: true
          description: Id of the object to be updated
      responses:
        '200':
          description: List of the entites
        '400':
          description: Bad parameters
        '404':
          description: No categories to list with the given parameter set.
        '500':
          description: Internal server error
    put:
      description: Create a new user
      operationId: v1_userUpdate
      parameters:
        - name: data
          in: body
          description: Payload to update a user
          schema:
            $ref: '#/definitions/user_create'
        - name: id
          in: path
          type: string
          required: true
          description: Id of the user to be updated
      responses:
        '200':
          description: List of the entites
        '400':
          description: Bad parameters
        '404':
          description: No categories to list with the given parameter set.
        '500':
          description: Internal server error
    delete:
      description: Delete a user
      operationId: v1_userDestroy
      parameters:
        - name: id
          in: path
          type: string
          required: true
          description: Id of the user to be updated
      responses:
        '200':
          description: List of the entites
        '400':
          description: Bad parameters
        '404':
          description: No categories to list with the given parameter set.
        '500':
          description: Internal server error
definitions:
  user_create:
    properties:
      _id:
        type: string
      name:
        type: string
